### ISSUE TITLE
listing should mention the line number

### ISSUE THREAD

**Issue by oupala** [davidxmoody/metalsmith-broken-link-checker#2]
The plugin is listing broken links on the console, giving some informations :

```
Warning: Link is broken: href: "undefined", text: "", in file: mypath\index.html
```

Feature request : it should also mention the line number as it may be hard to identify the broken link when we have many identical broken links, or when we have not much informations (such as "undefined" or emprty string "").

**Comment by davidxmoody** [comment]
Unfortunately, this isn't really possible with the way that cheerio parses html. Planning to add the ability to provide a custom link handling function which will be passed additional context about the link (including its full html) so that you could search for that in the generated site. This is similar to #4 so I'm going to close this and just leave that one open.
