### ISSUE TITLE
Support metalsmith-permalinks

### ISSUE THREAD

**Issue by thangngoc89** [davidxmoody/metalsmith-broken-link-checker#8]
I'm using [https://github.com/segmentio/metalsmith-permalinks](metalsmith-permalinks) to get a pretty url. 

It converts `about.html` into `about/index.html` . 

But this would fail the broken link check. I know that a simple regex would do the trick. But any plan to support it in the future?

**Comment by davidxmoody** [comment]
Hi, I'm not quite sure what you mean. The broken link checker plugin will only check the current state of the `files` object. That means if you have a link to `about.html` after permalinks has already converted it to `about/index.html` then it will in fact be a real broken link because any user following it will not reach the intended target. Links to either `about/` or `about/index.html` will still pass the broken link checker. This is the intended behavior. 

The broken link checker should be run after all modifications to the `files` object have taken place. If you are running it before permalinks has run then that could explain the problem. 

If this hasn't helped then could you please give me some more specific details.

**Comment by thangngoc89** [comment]
Sorry for the short issue report. This main issue is I don't write trailling slash in my url. 

I only write `about` and my webserver will redirect to `about/` and `about/index.html`

Could you consider add an option for this ?

**Comment by davidxmoody** [comment]
Thanks for explaining. Yes, I'd be happy to add that. I did consider it a while ago but wasn't sure if anybody would need it. 

I think I'll call the option `allowRedirects` and default it to false. I'll release a new version within the next few days.

**Comment by thangngoc89** [comment]
Thank you very much.

**Comment by davidxmoody** [comment]
Just published version 0.1.8 which adds a new `allowRedirects` option to address your issue. Let me know if you have any problems with it.

**Comment by thangngoc89** [comment]
Awesome. Thank you
